### ISSUE TITLE
Upload Source

### ISSUE THREAD

**Issue by ecp4224** [nenuadrian/qr-code-unity-3d-read-generate#1]
Why not upload source so people can fork/pull request to add support to newest Unity.

Or even just to maintain ?

**Comment by ashleyjamesbrown** [comment]
ditto the above comment ? Would like this to scan 2d barcodes as well.

**Comment by nenuadrian** [comment]
Apologies, I did not the save the source at the time - neither did I account for its usefulness - but I expected the library itself may stop being available for download hence uploaded it here, expecting code to be backwards compatbile which is likely to have stopped being
